logging:
  level:
    org.springframework.social: DEBUG

database:
  jdbc_url:
    jdbc:mysql://192.168.0.10:3306/meipin?allowMultiQueries=true
  jdbc_user:
    meipin
  jdbc_password:
    \!Passw0rd
  uuid:
    ${random.uuid}  
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me            
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
qq:
  client:
    clientId: 101328441
    clientSecret: a498bff6e628f058adac0d3734e2182b
    accessTokenUri: https://graph.qq.com/oauth2.0/token
    userAuthorizationUri: https://graph.qq.com/oauth2.0/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.qq.com/oauth2.0/me   
weibo:
  client:
    clientId: 3585285158
    clientSecret: 8b64f9c499b3860ae889c53891ebf5d9
    accessTokenUri: https://api.weibo.com/oauth2/access_token
    userAuthorizationUri: https://api.weibo.com/oauth2/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.weibo.com/oauth2/get_token_info       
spring:
  social:
    auto-connection-views: true
    facebook:
      app-id: 233668646673605
      app-secret: 33b17e044ee6a4fa383f46ec6e28ea1d      
    weibo:
      app-id: 3585285158
      app-secret: 8b64f9c499b3860ae889c53891ebf5d9
    qq:
      app-id: 101328441
      app-secret: a498bff6e628f058adac0d3734e2182b        
    wechat:
      app-id: wx7573a9d4c3809527
      app-secret: 23258e25fe5f9ae6023258e25fe5f9ae60         
  session:
    store-type: jdbc    
  mail:
    host: smtp.mxhichina.com
    username: admin@getxinfo.com
    password: "!Passw0rd"      
  datasource:
    url: jdbc:p6spy:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver        
security:      
  basic:
    enabled: false
  user:
    password: user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
authentication:
  policy:
    lockoutPeriodSeconds: 300
    lockoutAfterFailures: 5
    countFailuresWithinSeconds: 1200
password:
  policy:
    minLength: 0
    maxLength: 255
    requireUpperCaseCharacter: 0
    requireLowerCaseCharacter: 0
    requireDigit: 0
    requireSpecialCharacter: 0
    expirePasswordInMonths: 0 
login.url: http://localhost:8080/uaa
smtp.from_address: admin@getxinfo.com   
#server:
#  port: 80         